name: docs

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install sphinx furo sphinx-polyversion asyncio
          pip install -e .

      - name: Build versioned docs
        run: |
          sphinx-polyversion docs/poly.py

          touch docs/_build/html/.nojekyll
          echo '<meta http-equiv="refresh" content="0; url=main/">' > docs/_build/html/index.html

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
